# -*- coding: utf-8 -*-
"""pgm17

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PAXs52efc89TOWVk1cMVmzRBKtcTR3vM
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

student = pd.read_csv('/content/student_scores.csv')

print(student.head())
print(student.describe())
print(student.info())

Xax = student.iloc[:, 0]
Yax = student.iloc[:, 1]
plt.scatter(Xax, Yax)
plt.xlabel("No. of hours")
plt.ylabel("Score")
plt.title("Student scores")
plt.show()

x = student.iloc[:,:-1]
y = student.iloc[:, 1]
print('x values :\n', x)
print('y values :\n', y)

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2,
random_state=42)
regressor = LinearRegression()
regressor.fit(x_train, y_train)
print('INTERCEPT = ', regressor.intercept_)
print('COEFFICIENT = ', regressor.coef_[0])

y_pred = regressor.predict(x_test)
print("Actual vs Predicted values:")
for actual, predicted in zip(y_test, y_pred):
  print("Actual value:", actual, "Predicted value:", predicted)

mislabeled_points = np.sum(np.round(y_test) != np.round(y_pred))
print ("Number of mislabeled points from test data set :", mislabeled_points)

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Mean Squared Error:", mse)
print("R-squared:", r2)