# -*- coding: utf-8 -*-
"""program19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W_wC9FZMN4ag4h81NTrjQvUqP-HcIj2L
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
import numpy as np
customer = pd.read_csv('/content/Mall_Customers.csv')
points = customer.iloc[:, 3:5].values
x = points[:, 0]
y = points[:, 1]
plt.figure(figsize=(8, 6))
plt.scatter(x, y, s=50, alpha=0.7, c='blue')
plt.xlabel('Annual Income (k$)')
plt.ylabel('Spending Score (1-100)')
plt.title('Customer Data: Annual Income vs Spending Score')
plt.show()
def kmeans_clustering_and_plot(points, n_clusters):
  kmeans = KMeans(n_clusters=n_clusters, random_state=0)
  kmeans.fit(points)
  cluster_labels = kmeans.predict(points)
  cluster_centers = kmeans.cluster_centers_
  plt.figure(figsize=(8, 6))
  scatter = plt.scatter(x, y, c=cluster_labels, s=50, alpha=0.7, cmap='viridis')
  plt.scatter(cluster_centers[:, 0], cluster_centers[:, 1], s=200, c='red', marker='X', label='Centroids')
  plt.xlabel('Annual Income (k$)')
  plt.ylabel('Spending Score (1-100)')
  plt.title(f'K-Means Clustering with {n_clusters} Clusters')
  plt.legend()
  plt.colorbar(scatter, label="Cluster Label")
  plt.show()
  print(f"Cluster labels for K={n_clusters}:\n", cluster_labels)
  print(f"Cluster centers for K={n_clusters}:\n", cluster_centers)
for k in range(4, 9):
  kmeans_clustering_and_plot(points, n_clusters=k)